
from enum import Enum
class MultiFormatSchemaElseSchemaFormat1(Enum): 
  APPLICATION_SLASH_VND_DOT_OAI_DOT_OPENAPI_SEMICOLON_VERSION_EQUAL_3_DOT_0_DOT_0 = "application/vnd.oai.openapi;version=3.0.0"
  APPLICATION_SLASH_VND_DOT_OAI_DOT_OPENAPI_PLUS_JSON_SEMICOLON_VERSION_EQUAL_3_DOT_0_DOT_0 = "application/vnd.oai.openapi+json;version=3.0.0"
  APPLICATION_SLASH_VND_DOT_OAI_DOT_OPENAPI_PLUS_YAML_SEMICOLON_VERSION_EQUAL_3_DOT_0_DOT_0 = "application/vnd.oai.openapi+yaml;version=3.0.0"
  APPLICATION_SLASH_VND_DOT_APACHE_DOT_AVRO_SEMICOLON_VERSION_EQUAL_1_DOT_9_DOT_0 = "application/vnd.apache.avro;version=1.9.0"
  APPLICATION_SLASH_VND_DOT_APACHE_DOT_AVRO_PLUS_JSON_SEMICOLON_VERSION_EQUAL_1_DOT_9_DOT_0 = "application/vnd.apache.avro+json;version=1.9.0"
  APPLICATION_SLASH_VND_DOT_APACHE_DOT_AVRO_PLUS_YAML_SEMICOLON_VERSION_EQUAL_1_DOT_9_DOT_0 = "application/vnd.apache.avro+yaml;version=1.9.0"
  APPLICATION_SLASH_RAML_PLUS_YAML_SEMICOLON_VERSION_EQUAL_1_DOT_0 = "application/raml+yaml;version=1.0"